import level1 from 'public/levels/1level.tmx';
import level2 from 'public/levels/2level.tmx';
import level3 from 'public/levels/3level.tmx';
import level4 from 'public/levels/4level.tmx';
import level5 from 'public/levels/5level.tmx';
import level6 from 'public/levels/6level.tmx';
import level7 from 'public/levels/7level.tmx';
import level8 from 'public/levels/8level.tmx';
import level9 from 'public/levels/9level.tmx';
import level10 from 'public/levels/10level.tmx';
import level11 from 'public/levels/11level.tmx';
import level12 from 'public/levels/12level.tmx';
import level13 from 'public/levels/13level.tmx';
import level14 from 'public/levels/14level.tmx';
import level15 from 'public/levels/15level.tmx';
import level16 from 'public/levels/16level.tmx';
import level17 from 'public/levels/17level.tmx';
import level18 from 'public/levels/18level.tmx';
import level19 from 'public/levels/19level.tmx';
import level20 from 'public/levels/20level.tmx';
import level21 from 'public/levels/21level.tmx';
import level22 from 'public/levels/22level.tmx';
import level23 from 'public/levels/23level.tmx';

export const levels1 = [level1,level2,level3,level4,level5,level6,level7,level8,level9,level10,level11,level12,level13,level14,level15,level16,level17,level18,level19,level20,level21,level22];
export const levels = [level23];