import test from 'public/levels/test.tmx';
import level1 from 'public/levels/1level.tmx';
import level2 from 'public/levels/2level.tmx';
import level3 from 'public/levels/3level.tmx';
import level4 from 'public/levels/4level.tmx';
import level5 from 'public/levels/5level.tmx';
import level6 from 'public/levels/6level.tmx';
import level7 from 'public/levels/7level.tmx';
import level8 from 'public/levels/8level.tmx';
import level9 from 'public/levels/9level.tmx';
import level10 from 'public/levels/10level.tmx';
import level11 from 'public/levels/11level.tmx';
import level12 from 'public/levels/12level.tmx';
import level13 from 'public/levels/13level.tmx';
import level14 from 'public/levels/14level.tmx';
import level15 from 'public/levels/15level.tmx';
import level16 from 'public/levels/16level.tmx';
import level17 from 'public/levels/17level.tmx';
import level18 from 'public/levels/18level.tmx';
import level19 from 'public/levels/19level.tmx';
import level20 from 'public/levels/20level.tmx';
import level21 from 'public/levels/21level.tmx';
import level22 from 'public/levels/22level.tmx';
import level23 from 'public/levels/23level.tmx';
import level24 from 'public/levels/24level.tmx';
import level25 from 'public/levels/25level.tmx';
import level26 from 'public/levels/26level.tmx';
import level27 from 'public/levels/27level.tmx';
import level28 from 'public/levels/28level.tmx';
import level29 from 'public/levels/29level.tmx';
import level30 from 'public/levels/30level.tmx';

import level_egg_1 from 'public/levels/egg_1level.tmx';
import level_egg_2 from 'public/levels/egg_2level.tmx';
import level_egg_3 from 'public/levels/egg_3level.tmx';
import level_egg_4 from 'public/levels/egg_4level.tmx';
import level_egg_5 from 'public/levels/egg_5level.tmx';
import level_egg_6 from 'public/levels/egg_6level.tmx';
import level_egg_7 from 'public/levels/egg_7level.tmx';
import level_egg_8 from 'public/levels/egg_8level.tmx';
import level_egg_9 from 'public/levels/egg_9level.tmx';
import level_egg_10 from 'public/levels/egg_10level.tmx';
import level_egg_11 from 'public/levels/egg_11level.tmx';
import level_egg_12 from 'public/levels/egg_12level.tmx';
import level_egg_13 from 'public/levels/egg_13level.tmx';
import level_egg_14 from 'public/levels/egg_14level.tmx';
import level_egg_15 from 'public/levels/egg_15level.tmx';

export const levels = [level1,level2,level3,level4,level5,level6,level7,level8,level9,level10,level11,level12,level13,level14,level15,level16,level17,level18,level19,level20,level21,level22,level23,level24,level25,level26,level27, level28, level29, level30];
export const levels1 = [test];
export const eggs_levels1 = [level_egg_1,level_egg_2,level_egg_3,level_egg_4,level_egg_5,level_egg_6,level_egg_7,level_egg_8,level_egg_9,level_egg_10,level_egg_11,level_egg_12,level_egg_13,level_egg_14,level_egg_15];
export const eggs_levels = [level_egg_10,level_egg_11,level_egg_12,level_egg_13,level_egg_14,level_egg_15];
